USE stayease;

-- 1. Which room type is booked most often?

SELECT
    rt.name AS room_type,
    COUNT(*) AS booking_count
FROM reservations r
JOIN rooms rm
    ON r.room_id = rm.room_id
JOIN room_types rt
    ON rm.room_type_id = rt.room_type_id
GROUP BY rt.room_type_id, rt.name
ORDER BY booking_count DESC;

-- 2. What is the hotel occupancy rate?

SELECT
    COUNT(CASE WHEN status = 'Occupied' THEN 1 END) * 100.0
    / COUNT(*) AS occupancy_rate
FROM rooms;

-- 3. What is the average length of stay?

SELECT
    AVG(DATEDIFF(check_out, check_in)) AS average_length_of_stay
FROM reservations
WHERE status <> 'Cancelled';

-- 4. What is the revenue by room type?

SELECT
    rt.name AS room_type,
    SUM(p.amount) AS total_revenue
FROM payments p
JOIN reservations r
    ON p.reservation_id = r.reservation_id
JOIN rooms rm
    ON r.room_id = rm.room_id
JOIN room_types rt
    ON rm.room_type_id = rt.room_type_id
GROUP BY rt.room_type_id, rt.name
ORDER BY total_revenue DESC;

-- 5. Which guests have stayed more than once?

SELECT
    g.guest_id,
    g.name,
    COUNT(r.reservation_id) AS stay_count
FROM guests g
JOIN reservations r
    ON g.guest_id = r.guest_id
WHERE r.status <> 'Cancelled'
GROUP BY g.guest_id, g.name
HAVING COUNT(r.reservation_id) > 1;

-- 6. Which room types have the highest ratings?

SELECT
    rt.name AS room_type,
    AVG(rv.rating) AS average_rating
FROM reviews rv
JOIN reservations r
    ON rv.reservation_id = r.reservation_id
JOIN rooms rm
    ON r.room_id = rm.room_id
JOIN room_types rt
    ON rm.room_type_id = rt.room_type_id
GROUP BY rt.room_type_id, rt.name
ORDER BY average_rating DESC;

-- 7. What is the cancellation rate?

SELECT
    COUNT(CASE WHEN status = 'Cancelled' THEN 1 END) * 100.0
    / COUNT(*) AS cancellation_rate
FROM reservations;

-- 8. How much revenue was generated by each payment method?

SELECT
    method,
    SUM(amount) AS total_revenue
FROM payments
GROUP BY method
ORDER BY total_revenue DESC;

-- 9. Which services are used most often?

SELECT
    s.name AS service,
    SUM(su.quantity) AS total_quantity
FROM service_usage su
JOIN services s
    ON su.service_id = s.service_id
GROUP BY s.service_id, s.name
ORDER BY total_quantity DESC;

-- 10. What is the current status of all rooms?

SELECT
    status,
    COUNT(*) AS room_count
FROM rooms
GROUP BY status
ORDER BY room_count DESC;

-- 11. Which employees completed the most housekeeping tasks?

SELECT
    e.name AS employee_name,
    COUNT(h.task_id) AS completed_tasks
FROM employees e
JOIN housekeeping h
    ON e.employee_id = h.employee_id
WHERE h.status = 'Completed'
GROUP BY e.employee_id, e.name
ORDER BY completed_tasks DESC;

-- 12. How many available rooms are there for each room type?

SELECT
    rt.name AS room_type,
    COUNT(r.room_id) AS available_rooms
FROM room_types rt
JOIN rooms r
    ON rt.room_type_id = r.room_type_id
WHERE r.status = 'Available'
GROUP BY rt.room_type_id, rt.name
ORDER BY available_rooms DESC;

-- 13. Which reservations used hotel services?

SELECT
    r.reservation_id,
    g.name AS guest_name,
    COUNT(su.usage_id) AS services_used
FROM reservations r
JOIN guests g
    ON r.guest_id = g.guest_id
JOIN service_usage su
    ON r.reservation_id = su.reservation_id
GROUP BY r.reservation_id, g.name
ORDER BY services_used DESC;

-- 14. What is the total revenue generated by each service?

SELECT
    s.name AS service,
    SUM(s.price * su.quantity) AS service_revenue
FROM services s
JOIN service_usage su
    ON s.service_id = su.service_id
GROUP BY s.service_id, s.name
ORDER BY service_revenue DESC;

-- 15. Which employees have pending housekeeping tasks?

SELECT
    e.name AS employee_name,
    COUNT(h.task_id) AS pending_tasks
FROM employees e
JOIN housekeeping h
    ON e.employee_id = h.employee_id
WHERE h.status = 'Pending'
GROUP BY e.employee_id, e.name
ORDER BY pending_tasks DESC;
